2021-09-05 00:02:46,434 ERROR: Exception on /index [GET] [in /Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ozanunal/Desktop/Python/flask_app/app/routes.py", line 39, in index
    return render_template('index.html', title='Home', form=form,
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ozanunal/Desktop/Python/flask_app/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ozanunal/Desktop/Python/flask_app/app/templates/base.html", line 58, in template
    {% block content %}{% endblock %}
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2021-09-05 00:03:21,319 INFO: Microblog startup [in /Users/ozanunal/Desktop/Python/flask_app/app/__init__.py:32]
2021-09-05 00:03:24,440 ERROR: Exception on /index [GET] [in /Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ozanunal/Desktop/Python/flask_app/app/routes.py", line 39, in index
    return render_template('index.html', title='Home', form=form,
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ozanunal/Desktop/Python/flask_app/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ozanunal/Desktop/Python/flask_app/app/templates/base.html", line 69, in template
    {% block content %}{% endblock %}
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2021-09-05 00:03:39,392 INFO: Microblog startup [in /Users/ozanunal/Desktop/Python/flask_app/app/__init__.py:32]
2021-09-05 00:05:24,735 INFO: Microblog startup [in /Users/ozanunal/Desktop/Python/flask_app/app/__init__.py:32]
2021-09-05 00:05:29,492 ERROR: Exception on /index [GET] [in /Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/ozanunal/Desktop/Python/flask_app/app/routes.py", line 39, in index
    return render_template('index.html', title='Home', form=form,
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ozanunal/Desktop/Python/flask_app/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/ozanunal/Desktop/Python/flask_app/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block 'doc'
    {%- block html %}
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block 'html'
    {% block body -%}
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block 'body'
    {% block navbar %}
  File "/Users/ozanunal/Desktop/Python/flask_app/app/templates/base.html", line 17, in block 'navbar'
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Users/ozanunal/Desktop/Python/flask_app/flaskwork/lib/python3.8/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'index' instead?
2021-09-05 00:10:54,029 INFO: Microblog startup [in /Users/ozanunal/Desktop/Python/flask_app/app/__init__.py:32]
2021-09-05 00:11:28,301 INFO: Microblog startup [in /Users/ozanunal/Desktop/Python/flask_app/app/__init__.py:32]
2021-09-05 00:14:12,632 INFO: Microblog startup [in /Users/ozanunal/Desktop/Python/flask_app/app/__init__.py:35]
